version: '3.5'
services:
  mysql:
    image: mysql/mysql-server:latest-aarch64
    container_name: school_registration
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: 'school_registration'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    restart: always
